import warnings

from lys.errors import NotImplementedWarning

from .CanvasBase import saveCanvas
from .WaveData import WaveData3D


class LineData(WaveData3D):
    """
    Interface to access line data in the canvas.

    Instance of LineData is automatically generated by display or append methods.

    """

    @saveCanvas
    def setColor(self, color):
        self.__setAppearance("color", color)
        self._setColor(color)

    def __setAppearance(self, key, value):
        self._appearance[key] = value

    def __getAppearance(self, key, default=None):
        return self._appearance.get(key, default)

    def _loadAppearance(self, appearance):
        pass

    def _setColor(self, color):
        warnings.warn(str(type(self)) + " does not implement _setColor(color) method.", NotImplementedWarning)

    def _showEdges(self, b):
        warnings.warn(str(type(self)) + " does not implement _showEdges(b) method.", NotImplementedWarning)
