import warnings

from lys.errors import NotImplementedWarning

from .CanvasBase import saveCanvas
from .WaveData import WaveData3D


class SurfaceData(WaveData3D):
    """
    Interface to access surface data in the canvas.

    Instance of SurfaceData is automatically generated by display or append methods.

    """

    @saveCanvas
    def setColor(self, color, type="scalars"):
        self.__setAppearance("colorType", type)
        self.__setAppearance("color", color)
        self._setColor(color, type)

    def showEdges(self, b):
        self.__setAppearance("showEdges", b)
        self._showEdges(b)

    def __setAppearance(self, key, value):
        self._appearance[key] = value

    def __getAppearance(self, key, default=None):
        return self._appearance.get(key, default)

    def _loadAppearance(self, appearance):
        pass

    def _setColor(self, color, type):
        warnings.warn(str(type(self)) + " does not implement _setColor(color, type) method.", NotImplementedWarning)

    def _showEdges(self, b):
        warnings.warn(str(type(self)) + " does not implement _showEdges(b) method.", NotImplementedWarning)
