import warnings

from lys.errors import NotImplementedWarning

from .CanvasBase import saveCanvas
from .WaveData import WaveData3D


class SurfaceData(WaveData3D):
    """
    Interface to access surface data in the canvas.

    Instance of SurfaceData is automatically generated by display or append methods.

    """

    def __setAppearance(self, key, value):
        self._appearance[key] = value

    def __getAppearance(self, key, default=None):
        return self._appearance.get(key, default)

    def _loadAppearance(self, appearance):
        pass
